"""migración 1

Revision ID: fe8822648f92
Revises: 
Create Date: 2025-03-22 15:40:30.663507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe8822648f92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.alter_column('organigrama_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.alter_column('organigrama_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.alter_column('organigrama_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.alter_column('organigrama_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
